FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
COPY tsconfig.json ./
COPY src ./src
RUN npm install
RUN npm run build
EXPOSE 4173
CMD ["npx", "serve", "dist", "-s", "-l", "4173"]
